### ISSUE TITLE
Correção da iteração 0

### ISSUE THREAD

**Issue by ps1312** [vitorlima-vl/Vaccinate#1]
Olá pessoal, vou dar o feedback pra vocês das entregas da iteração 0:

## Ata de reunião:
* Participantes da reunião -> ok
* Tópicos discutidos -> ok
* O que foi definido -> ok
* Formato Markdown -> Não, foi entregue no formato .pdf (-2 pontos)
### nota final: 8

--------------------------------------------------------------------------------------------------------------

## Preenchimento do GitHub:
* Nome do projeto -> ok
* Descrição do projeto -> Não (-3 pontos)
* Justificativa do projeto -> Não (-3 pontos)
* Especificação do papel dos membros -> ok
### nota final: 4

>Pessoal, não encontrei nem a descrição e nem a justificativa do projeto de vocês..

--------------------------------------------------------------------------------------------------------------
## Mockups e storyboards:
* Mockups -> ok
* Storyboard -> ok
### nota final: 10

**Comment by ps1312** [comment]
Galera, continuando a correção da iteração 0

## Histórias de usuário:
* Não entregue
### nota final: 0

--------------------------------------------------------------------------------------------------------------
## Postmortem:
* Não entregue
### nota final: 0

>Pessoal, não encontrei nem a o postmortem e nem a as histórias do usuário de vocês..

**Comment by vinicius3w** [comment]
não vão fechar?
