### ISSUE TITLE
Feedback Teste TDD e BDD - IT04

### ISSUE THREAD

**Issue by lsca** [vitorlima-vl/Vaccinate#22]
Sem testes.

Nota final: 0

Qualquer duvida, só responder essa issue, caso contrario só fecha-la

Att,

**Comment by Lerissonf** [comment]
# Feedback Teste TDD e BDD - IT04
Bom dia, pessoal desculpa o atraso, pois Serra estava atarefado e pediu para eu corrigir os testes de vcs, já que também ele não tinha visto que vcs deram um fork.
### Atraso na entrega -> não

### Testes BDD:
- Não possui nenhum caminho triste -> Possuem caminhos tristes e felizes.
- Todos os testes verdes -> sim
---
![image](https://user-images.githubusercontent.com/20325833/41846990-e6d9be48-784e-11e8-8abd-605d4f6f0525.png)

---
![image](https://user-images.githubusercontent.com/20325833/41847058-1fc32a50-784f-11e8-8920-193e6abb356a.png)
## Nota BDD: 5.0
---
### Testes TDD:
- Todos os testes verdes -> sim
- Cobertura de testes -> Muito pequena, desenvolver mais.(-2)
---
![image](https://user-images.githubusercontent.com/20325833/41847344-10c47170-7850-11e8-8105-20c7e14bfb95.png)

## Nota TDD:  3.0
---
# Nota Final: 5.0 + 3.0 = 8.0
