### ISSUE TITLE
Feedback Screencast - Iteração 4

### ISSUE THREAD

**Issue by mateusc42** [vitorlima-vl/Vaccinate#23]
Iae pessoal, vou passar o feedback do Screencast da iteração 4 de vocês. :)

## Screencast:
<ul>
  <li>Tempo mínimo de 3 minutos -> video com apenas 2.</li>
</ul>

#### Nota Final: 9
---------------------------------------------------------------
> **Nota:** Adicionem a Label de FeedBack, não posso fazer isso porque não estou no projeto. Obrigado.

**Comment by Eslovenio** [comment]
O screencast foi feito no seguinte fork : https://github.com/RuanAV/Vaccinate

**Comment by mateusc42** [comment]
Sorry, erro meu. Não vi que vocês tinham um fork. Corrigi a nota. :)
